config/routes.rb
LifeFeed::Application.routes.draw do
  resources :feed_items
  match '/github' => 'feed_items#github'
  match '/heroku' => 'feed_items#heroku'
  match '/mention' => 'feed_items#create'
  root to: 'feed_items#index'

end

app/models/feed_item.rb
class FeedItem < ActiveRecord::Base
  attr_accessible :message, :source, :title
  after_create :update_clients
  
  def update_clients
    Pusher['feed-updates'].trigger('new-item', self.to_json)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  def help
    Helper.instance
  end

  class Helper
    include Singleton
    include ActionView::Helpers::TextHelper
  end
end

app/controllers/feed_items_controller.rb
class FeedItemsController < ApplicationController
  # GET /feed_items
  # GET /feed_items.json
  def index
    @feed_items = FeedItem.order('created_at desc').limit(10)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @feed_items }
    end
  end

  # POST /feed_items
  # POST /feed_items.json
  def create
    @feed_item = FeedItem.new(params[:feed_item])

    respond_to do |format|
      if @feed_item.save
        format.html { redirect_to @feed_item, notice: 'Feed item was successfully created.' }
        format.json { render json: @feed_item, status: :created, location: @feed_item }
      else
        format.html { render action: "new" }
        format.json { render json: @feed_item.errors, status: :unprocessable_entity }
      end
    end
  end

  def github
    params['payload'] = JSON.parse(params['payload'])
    author = params['payload']['commits'][0]['author']['name']
    repo_name = params['payload']['repository']['name']
    commits = params['payload']['commits']
    @feed_item = FeedItem.new(source: 'github')
    @feed_item.title = "#{repo_name} updated"
    @feed_item.subtitle = "by #{author}"
    @feed_item.message = "#{author} pushed #{help.pluralize(commits.size, 'new commit')} to #{repo_name}"
    @feed_item.save
    render nothing: true
  end

  def heroku
    app = params['app']
    user = params['user']
    url = params['url']
    @feed_item = FeedItem.new(source: 'heroku')
    @feed_item.title = "#{app} redeployed"
    @feed_item.subtitle = "by #{user}"
    @feed_item.message = "#{user} just deployed a new version of <a href='#{url}'>#{app}</a>"
    @feed_item.save
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  include Twitter::Autolink
end

app/helpers/feed_items_helper.rb
module FeedItemsHelper
end

app/views/feed_items/_form.html.erb
<%= form_for(@feed_item) do |f| %>
  <% if @feed_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@feed_item.errors.count, "error") %> prohibited this feed_item from being saved:</h2>

      <ul>
      <% @feed_item.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :message %><br />
    <%= f.text_area :message %>
  </div>
  <div class="field">
    <%= f.label :source %><br />
    <%= f.text_field :source %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/feed_items/edit.html.erb
<h1>Editing feed_item</h1>

<%= render 'form' %>

<%= link_to 'Show', @feed_item %> |
<%= link_to 'Back', feed_items_path %>

app/views/feed_items/index.html.erb
<div id="feed-items">
  <% @feed_items.each do |feed_item| %>
    <div class="row">
      <article class="span8 offset2 feed-item <%= feed_item.source %>">
        <header>
          <%= image_tag "#{feed_item.source}.png" %>
          <h1><%= feed_item.title %><small><%= feed_item.subtitle %></small></h1>
        </header>
        <div class="feed-item-inner">
          <%= auto_link(feed_item.message.html_safe).html_safe %>
        </div>
      </article>
    </div>
  <% end %>
</div>

<script type="text/html" id="feed-item-template">
  <div class="row">
    <article class="span8 offset2 feed-item {{source}}">
      <header>
        <img src="/assets/{{source}}.png"/>
        <h1>{{title}}<small>{{subtitle}}</small></h1>
      </header>
      <div class="feed-item-inner">
        {{{message}}}
      </div>
    </article>
  </div>
</script>

app/views/feed_items/new.html.erb
<h1>New feed_item</h1>

<%= render 'form' %>

<%= link_to 'Back', feed_items_path %>

app/views/feed_items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @feed_item.title %>
</p>

<p>
  <b>Message:</b>
  <%= @feed_item.message %>
</p>

<p>
  <b>Source:</b>
  <%= @feed_item.source %>
</p>


<%= link_to 'Edit', edit_feed_item_path(@feed_item) %> |
<%= link_to 'Back', feed_items_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>LifeFeed</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "https://raw.github.com/twitter/twitter-text-js/master/pkg/twitter-text-1.4.16.js", "https://raw.github.com/janl/mustache.js/master/mustache.js", "http://js.pusher.com/1.11/pusher.min.js", "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="container">
  <%= yield %>
</div>

</body>
</html>